-- TO BE RUN AFTER A FIRST RUN OF THE SITE (IN ORDER TO CREATE THE DB AND TABLES)
 -- RUN WITH : $ sqlite3 db.sqlite < db_init.sql

 --DEPARTMENT
DELETE FROM department;
INSERT INTO department (name) VALUES
	('Roya'),
	('Vésubie'),
	('Tinée'),
	('Haut-Var Cians'),
	('Ubaye Verdon'),
	('CGP');

 --PEOPLE
DELETE FROM people;
INSERT INTO people (name, surname, department_id) VALUES
	("Aurelien","COLLENOT",1),
	("Thomas","LEBARD",1),
	("Emilie","GIORDANO",1),
	("Florent","CHAPELUT",1),
	("Laurent","ZIMMERMANN",1),
	("Laurent","MALTHIEUX",1),
	("Stéphane","COMBEAUD",1),
	("Sylvain","CRISTINI",2),
	("Jean-Luc","PARDI",2),
	("Barbara","BIANCO",2),
	("Philippe","ARCHIMBAUD",2),
	("Franck","GUIGO",2),
	("Patrick","ORMEA",2),
	("Jean-Michel","GUSMEROLI",2),
	("Boris","OPOLKA",3),
	("Anthony","TURPAUD",3),
	("Evelyne","CLEMENT",3),
	("Hervé","BROSIUS",3),
	("Olivier","MONTIGNY",3),
	("Xavier","BONNET",3),
	("Mathieu","KRAMMER",3),
	("Jean-Pierre","BERGEON",3),
	("Albin","LIBORIO",4),
	("Christophe","GORGERAT",4),
	("Laurence","CABOUFIGUE",4),
	("Marion","BENSA",4),
	("Marc","EVENOT",4),
	("Jean-Paul","MANDINE",4),
	("Laurent","MARTIN DHERMONT",4),
	("Xavier","FRIBOURG",5),
	("Marie-Hélène","DA COSTA",5),
	("Sandy","LANTELME",5),
	("Sylvie","CLAUDON",5),
	("Sophie","ROUX",5),
	("Jean-Louis","MICHEL",5),
	("Olivier","LAURENT",5),
	("Ludovic","KLEIN",5),
	("J-F","CATY",5),
	("Julie","REY",5),
	("François","BRETON",5),
	("Jean-Luc","DUNAND",5),
	("Christian","JOULOT",5),
	("Georges","LOMBARD",5),
	("Guy","REBATTU",5),
	("Didier","WARNET",6),
	("Jean-Marc","CULOTTA",6),
	("Nathalie","SIEFERT",6),
	("Yvette","TRUCHI",6),
	("Marie-France","LECCIA",6),
	("Daniel","DEMONTOUX",6),
	("Claire","CRASSOUS",6),
	("Monique","PERFUS",6),
	("Clémentine","ASSMANN",6),
	("Marie","CANUT",6),
	("Isabelle","LHOMMEDET",6);

 --ANIMALS
DELETE FROM tagged_animal;
INSERT INTO tagged_animal (name, gender, ears, catch_date, picture) VALUES
	('Merveilles','female','Blanc - Violet','26/04/2016','merveilles.jpg'),
	('Bise','female','Blanc - Bleu','26/04/2016','bise.jpg'),
	('Roya','female','Bleu - Jaune','26/04/2016','roya.jpg'),
	('Lucille','female','Vert - Blanc','26/04/2016','lucille.jpg'),
	('Jump','male','Vert - Blanc','26/04/2016','jump.jpg'),
	('Piercing','male','Blanc - Aucune','27/04/2016','piercing.jpg'),
	('Choupinet','male','Violet - Bleu','27/04/2016','choupinet.jpg'),
	('Bou','male','Blanc - Rouge','27/04/2016','bou.jpg'),
	('Jo','male','Violet - Violet','24/04/2015','jo.jpg'),
	('Luc Alphand','male','Rouge - Vert','26/04/2016','luc_alphand.jpg'),
	('Rocco','male','Blanc - Jaune','27/04/2016','rocco.jpg'),
	('Steph','male','Rouge - Jaune','29/04/2015','steph.jpg'),
	('Thomas','male','Pistache - Pistache','27/04/2016','thomas.jpg'),
	('Pompon','male','Vert - Vert','28/04/2015','none.jpg'),
	('Pomponette','female','Violet - Violet','28/04/2015','none.jpg'),
	('Lorraine','female','Vert - Vert','28/04/2015','none.jpg'),
	('Marie','female','Rouge - Rouge','28/04/2015','none.jpg'),
	('Monsieur Delacour','male','Bleu - Bleu','28/04/2015','none.jpg'),
	('Silou','female','Bleu - Bleu','28/04/2015','none.jpg'),
	('Nath','male','Jaune - Rouge','28/04/2015','none.jpg'),
	('Patrick','male','Rouge - Rouge','29/04/2015','none.jpg'),
	('Neige','male','Blanc - Blanc','29/04/2015','none.jpg'),
	('Guillaumette','female','Blanc - Blanc','26/04/2016','none.jpg'),
	('Steph','female','Jaune - Violet','26/04/2016','none.jpg');
